// <auto-generated />
using System;
using CSHonorsTemplate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSHonorsTemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251105164057_PersonInAttendance")]
    partial class PersonInAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSHonorsTemplate.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<bool>("isPresent")
                        .HasColumnType("bit");

                    b.HasKey("AttendanceId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("PersonId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<int?>("ClubTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeetingDay")
                        .HasColumnType("int");

                    b.Property<int?>("MeetingFrequency")
                        .HasColumnType("int");

                    b.Property<string>("MeetingLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("MeetingTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeracrossId")
                        .HasColumnType("int");

                    b.HasKey("ClubId");

                    b.HasIndex("ClubTypeId");

                    b.ToTable("Clubs", (string)null);
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.ClubType", b =>
                {
                    b.Property<int>("ClubTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubTypeId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClubTypeId");

                    b.ToTable("ClubType");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Join", b =>
                {
                    b.Property<int>("JoinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JoinId"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("JoinId");

                    b.HasIndex("ClubId");

                    b.HasIndex("PersonId");

                    b.ToTable("Joins", (string)null);
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<string>("Agenda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MeetingId");

                    b.HasIndex("ClubId");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Attendance", b =>
                {
                    b.HasOne("CSHonorsTemplate.Models.Meeting", null)
                        .WithMany("Attendances")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSHonorsTemplate.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Club", b =>
                {
                    b.HasOne("CSHonorsTemplate.Models.ClubType", "ClubType")
                        .WithMany("Clubs")
                        .HasForeignKey("ClubTypeId");

                    b.Navigation("ClubType");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Join", b =>
                {
                    b.HasOne("CSHonorsTemplate.Models.Club", "Club")
                        .WithMany("Joins")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSHonorsTemplate.Models.Person", "Person")
                        .WithMany("Joins")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Meeting", b =>
                {
                    b.HasOne("CSHonorsTemplate.Models.Club", "Club")
                        .WithMany("Meetings")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Club", b =>
                {
                    b.Navigation("Joins");

                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.ClubType", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Meeting", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("CSHonorsTemplate.Models.Person", b =>
                {
                    b.Navigation("Joins");
                });
#pragma warning restore 612, 618
        }
    }
}
